#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-init

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - floorplan.tcl
  - pin-assignments.tcl
  - dont-use-cells.tcl

